Update manna-harbour_miryoku.c
Attempting to resolve

```
users/manna-harbour_miryoku/manna-harbour_miryoku.c: In function 'td_cg_togg_fn':
users/manna-harbour_miryoku/manna-harbour_miryoku.c:43:14: error: unsigned conversion from 'int' to 'uint8_t' {aka 'unsigned char'} changes value from '28701' to '29' [-Werror=overflow]
     tap_code(CG_TOGG);
              ^~~~~~~
users/manna-harbour_miryoku/manna-harbour_miryoku.c: In function 'td_cg_norm_fn':
users/manna-harbour_miryoku/manna-harbour_miryoku.c:50:14: error: unsigned conversion from 'int' to 'uint8_t' {aka 'unsigned char'} changes value from '28700' to '28' [-Werror=overflow]
     tap_code(CG_NORM);
              ^~~~~~~
```

By using tap_code16() instead of tap_code(), since apparently Magic Keycodes CG_TOGG and CG_NORM are 16-bit keycodes.